name: Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  pipeline:
    uses: theSamsCo/central-workflows/.github/workflows/pipeline.yaml@v1
    with:
      env: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      app_name: spi-api-1
      gcp_wif_provider: ${{ vars.GCP_WIF_PROVIDER_DEV }}
      gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      gcp_location: ${{ vars.GCP_LOCATION }}
      gitops_repo: ${{ vars.GITOPS_REPO }}
      #gitops_values_path: ${{ vars.GITOPS_VALUES_PATH }}
